print("twenkle, twenkle,little star,")
print("\t how i wonder what you are!")
print("\t\tup above the world so high,")
print("\t\tlike a diamond in the sky")
print("twenkle,twenkle,little star,")
print("\thow i wonder what you are!")
